# Docker Compose 配置文件 - 简化的交叉编译版本

services:
  wallpaper-explorer-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallpaper-explorer-windows-builder
    environment:
      # Rust构建优化
      CARGO_TARGET_DIR: "/tmp/target"
      CARGO_INCREMENTAL: "0"
      RUST_BACKTRACE: "1"
    volumes:
      # 输出目录
      - ./dist:/app/dist:rw
      # Cargo缓存
      - cargo-cache:/usr/local/cargo/registry:rw
      - cargo-git-cache:/usr/local/cargo/git:rw

volumes:
  cargo-cache:
    driver: local
  cargo-git-cache:
    driver: local
networks:
  default:
    name: wallpaper-explorer-build-network
    driver: bridge 